### ISSUE TITLE
Errore

### ISSUE THREAD

**Issue by stefanojan** [gicamm/homeassistant-comelit#2]
Mi potete aiutare? Mi da questo errore:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/comelit/__init__.py", line 67, in setup
    schema = VEDO_SCHEMA(vedo_conf)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['porta']

**Comment by iw6ovz** [comment]
Sei riuscito a trovare il seriale??
Non capisco come e dove impartire il comando pe rilevarlo

**Comment by stefanojan** [comment]
Lo preso dal sito http://www.comelitdns.com/ se effettui il login ti esce il codice seriale. Sarà quello???

**Comment by stefanojan** [comment]
No mi da l errore riportato sopra. Ma a me interessa solo la parte di vedo. Non ho proprio idea dell' Hub

**Comment by iw6ovz** [comment]
Vedo mi pare funzioni. Non espone i sensori però.

**Comment by gicamm** [comment]
Scusate l'enorme ritardo, ma ho avuto un problema con le notifiche di github.
Posso esserti ancora di aiuto?
