### ISSUE TITLE
Covers don't work

### ISSUE THREAD

**Issue by vincenzomazzeo** [gicamm/homeassistant-comelit#62]
Cover entities are not added:

2024-03-13 12:59:24.448 ERROR (MainThread) [homeassistant.components.cover] Error adding entity None for domain cover with platform comelit
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entities
await coro
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 784, in _async_add_entity
supported_features=entity.supported_features,
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 351, in supported_features
if self.current_cover_position is not None:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/comelit/cover.py", line 45, in current_cover_position
return 100 - self._position
~~~~^~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

**Comment by dinamitebla** [comment]
#66 should have fixed the issue
