### ISSUE TITLE
ONE thermostats not detected

### ISSUE THREAD

**Issue by Just-inc-ace** [gicamm/homeassistant-comelit#71]
The thermostats included in the ONE device is not detected as thermostat, only as sensor.
I did some debugging and it seems it has a different subtype (12):
`{"req_type":0,"req_sub_type":-1,"obj_id":"DOM#CL#66.1","out_data":[{"id":"DOM#CL#66.1","type":9,"sub_type":12,"sched_status":"0","status":"0","powerst":"1","temperatura":"206","auto_man":"2","est_inv":"1","soglia_attiva":"198","out_value_inv":"0","out_value_est":"0","dir_out_inv":"0","dir_out_est":"0","semiauto_enabled":"0"}]}`

So, I modified this in hub.py
` # skip creating the climate sensor for the PT100 sensor and add compatibility for ONE
                    if HubFields.SUB_TYPE in item and (item["sub_type"] == 16 or item["sub_type"] == 12):
                        self.update_climate(id, description, item)`

But when I do this I get an error, as the ONE (not ONE/H) has no humidity sensor on board.
`2024-04-25 18:23:22.073 ERROR (MainThread) [homeassistant.components.climate] Error adding entity climate.comelit_climate_living for domain climate with platform comelit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 890, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1334, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1058, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 328, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 539, in state_attributes
    if (current_humidity := self.current_humidity) is not None:
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 328, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comelit/climate.py", line 66, in current_humidity
    return self._state['measured_humidity']
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'measured_humidity'`

I can bypass the error by modifying this in climate.py:
`    @property
    def current_humidity(self):     
        return self._state['measured_humidity']`
in
`   @property
    def current_humidity(self):     
return 10`

But this is just a workaround for debugging.
How could I fix this properly?
I had a look, but I'm not a programmer, so can you point me in the right direction.

**Comment by gicamm** [comment]
You could write something like

```
@property
def current_humidity(self):
    return self._state.get('measured_humidity', None)
```

It returns the default value (None) when a dictionary key is not found.

**Comment by Just-inc-ace** [comment]
Ok it worked, I created a pull request. 
Closing.
