### ISSUE TITLE
Problema ultimo aggiornamento

### ISSUE THREAD

**Issue by Nicolalabbate** [gicamm/homeassistant-comelit#74]
Buongiorno,  dopo l'ultimo aggiornamento alla versione 2024.5.1 del core, lo stato delle luci e delle tapparelle non si aggiorna. È un problema solo mio?
Grazie

**Comment by gicamm** [comment]
La nuova versione appena rilasciata dovrebbe risolvere

**Comment by Nicolalabbate** [comment]
Ok, grazie

**Comment by Nicolalabbate** [comment]
Ho notato questo problema tra i log:
Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.comelit.hub
Fonte: custom_components/comelit/hub.py:306
Integrazione: Comelit SimpleHome/Vedo (documentazione, problemi)
Prima occorrenza: 17:52:04 (8 occorrenze)
Ultima registrazione: 18:06:15

Error updating sensor Detected that custom integration 'comelit' calls async_write_ha_state from a thread at custom_components/comelit/comelit_device.py, line 41: self.async_schedule_update_ha_state(). Please report it to the author of the 'comelit' custom integration.
Traceback (most recent call last):
  File "/config/custom_components/comelit/hub.py", line 306, in update_sensor
    self.add_or_update_sensor(sensor, value)
  File "/config/custom_components/comelit/hub.py", line 318, in add_or_update_sensor
    self.sensors[name].update_state(value)
  File "/config/custom_components/comelit/comelit_device.py", line 41, in update_state
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1258, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'comelit' calls async_write_ha_state from a thread at custom_components/comelit/comelit_device.py, line 41: self.async_schedule_update_ha_state(). Please report it to the author of the 'comelit' custom integration.

**Comment by gicamm** [comment]
la nuova versione 0.9.7 non dovrebbe presentare questo errore

**Comment by Nicolalabbate** [comment]
OK, aggiornato e risolto. Grazie
