### ISSUE TITLE
Unable to install the component

### ISSUE THREAD

**Issue by mario-rossi78** [gicamm/homeassistant-comelit#84]
Hi,
I tried to add the comelit component to my HA with the following parameters (in **bold** the info that I modified, the X are for privacy)

# Comelit Hub/Vedo
comelit:
  hub:
    host: **192.168.1.XXX**
    port: 1883
    mqtt-user: hsrv-user
    mqtt-password: sf1nE9bjPc
    username: '**admin**'
    password: '**admin**'
    serial: **0025291717XX**(two letters)
    client: homeassistant
    scan_interval: 2
  vedo:
    host: VEDO IP ADDRESS
    port: 80
    password: 'VEDO PASSWORD'
    scan_interval: 30
    binary_sensors: disable

But I can't get it to work. This is the log of the error.

Registratore: homeassistant.setup
Fonte: setup.py:402
Prima occorrenza: 15:47:06 (1 occorrenze)
Ultima registrazione: 15:47:06

Error during setup of component comelit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 402, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comelit/__init__.py", line 56, in setup
    hub = ComelitHub(hub_client, hub_serial, hub_host, mqtt_port, mqtt_user, mqtt_password, hub_user,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comelit/hub.py", line 226, in __init__
    self.client.connect(hub_host, mqtt_port, 45)
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

Last year I tried HA on a laptop and figured out how to configure the comelit component correctly, but I don't remember how.

Would you be able to help me?

Many thanks.

**Comment by mario-rossi78** [comment]
the IP address was incorrect

**Comment by mario-rossi78** [comment]
the ip address was incorrect

**Comment by mario-rossi78** [comment]
The IP was incorrect and the part of the code for VEDO has to be commented because I don't have vedo
